### ISSUE TITLE
set_shell not working

### ISSUE THREAD

**Issue by 0xjohn** [dsypniewski/SimpleSH#1]
When I try to change my shell to another available interpreters as you said I got an error about invalid shell specified.

for example:
```
> set_shell powershell
Error: invalid shell specified [{0}]
[1]
```
Please check it.

**Comment by dsypniewski** [comment]
Setting shells for cmd and powershell is done through `set_shell powershell.exe` and `set_shell cmd.exe`, please let me know if this solves Your problem.

**Comment by 0xjohn** [comment]
Worked like a charm!
Thanks!
